export default function Support() {
  return (
    <>
      <nav className="navbar">
        <a href="/" className="nav-logo">
          <img src="/images/icon.png" alt="DodotX" />
          <span>Dodot<span className="x">X</span></span>
        </a>
        <ul className="nav-links">
          <li><a href="/#features">Features</a></li>
          <li><a href="/privacy">Privacy</a></li>
          <li><a href="/terms">Terms</a></li>
          <li><a href="/support">Support</a></li>
        </ul>
      </nav>

      <div className="support-page">
        <h1>Support</h1>
        <p className="subtitle">
          Need help with DodotX? We're here for you.<br />
          Reach out and we'll get back to you within 24 hours.
        </p>

        <div className="support-cards">
          <div className="support-card">
            <div className="icon">📧</div>
            <div>
              <h3>Email Support</h3>
              <p>For any questions, issues, or feedback:<br />
              <a href="mailto:support@dodotx.net">support@dodotx.net</a></p>
            </div>
          </div>

          <div className="support-card">
            <div className="icon">🔑</div>
            <div>
              <h3>Forgot Password</h3>
              <p>Use the "Forgot Password" option on the Sign In screen. We'll send a 6-digit reset code to your registered email address. The code expires in 15 minutes.</p>
            </div>
          </div>

          <div className="support-card">
            <div className="icon">👶</div>
            <div>
              <h3>Adding Children</h3>
              <p>Go to Parent Dashboard → Settings. Create a child profile with a nickname and avatar. Share the family code so they can join from their own device.</p>
            </div>
          </div>

          <div className="support-card">
            <div className="icon">🗑️</div>
            <div>
              <h3>Delete Account or Data</h3>
              <p>Parents can delete child profiles from Settings. To delete your entire account, email us at <a href="mailto:support@dodotx.net">support@dodotx.net</a> and we'll process it within 30 days.</p>
            </div>
          </div>
        </div>

        <div className="faq">
          <h2>Frequently Asked Questions</h2>

          <div className="faq-item">
            <h3>Is DodotX free?</h3>
            <p>DodotX is free to download and use with all core features. We may introduce optional premium features in the future.</p>
          </div>

          <div className="faq-item">
            <h3>Does my child need an email to use DodotX?</h3>
            <p>No. Children join using a parent-generated family code and a nickname. No email, password, or personal information is needed for children.</p>
          </div>

          <div className="faq-item">
            <h3>What is the family code?</h3>
            <p>The family code is a 6-character code generated by the parent. It expires every 60 minutes for security. You can regenerate it anytime from Settings.</p>
          </div>

          <div className="faq-item">
            <h3>Can grandparents view my child's progress?</h3>
            <p>Yes! Use the "Visitor View" feature. Share the family code with them — they can view progress without creating an account. It's completely read-only.</p>
          </div>

          <div className="faq-item">
            <h3>Is my child's data safe?</h3>
            <p>Absolutely. We're COPPA compliant, collect minimal data (nickname + age only), use no tracking or ads, and parents have full control over all child data. See our <a href="/privacy">Privacy Policy</a> for details.</p>
          </div>

          <div className="faq-item">
            <h3>What platforms does DodotX support?</h3>
            <p>DodotX is available on iOS, Android, and web. You can use it on phones, tablets, and desktop browsers.</p>
          </div>
        </div>
      </div>

      <footer className="footer">
        <div className="footer-links">
          <a href="/privacy">Privacy Policy</a>
          <a href="/terms">Terms of Service</a>
          <a href="/support">Support</a>
        </div>
        <p className="footer-copy">&copy; 2026 DodotX. All rights reserved.</p>
      </footer>
    </>
  );
}
